### ISSUE TITLE
Configuration disappeared

### ISSUE THREAD

**Issue by Sei969** [TheCaduceus/Multi-Cloud-Transfer-Tool#15]
Hello and many thanks for this tool!

Yesterday I installed everything correctly and even the transfers went great, but today reconnecting the mounted drives are gone. Only the sample_data folder is present. What happened?

**Comment by TheCaduceus** [comment]
@Sei969 Google Colab provides temporary Runtimes which got deleted upon inactivity or when you close your Browser Tab, so all your configurations got deleted from Runtime, but as stated! MCT Tool saves those configurations in your Google Drive of Google Account that you connect before using the tool, you just need to fetch them using the option provided in tool. You can also check you Google Drive! there will be a folder named `MCT`.

**Comment by Sei969** [comment]
Thanks... Your tool is amazing!

**Comment by Sei969** [comment]
> @Sei969 Google Colab provides temporary Runtimes which got deleted upon inactivity or when you close your Browser Tab, so all your configurations got deleted from Runtime, but as stated! MCT Tool saves those configurations in your Google Drive of Google Account that you connect before using the tool, you just need to fetch them using the option provided in tool. You can also check you Google Drive! there will be a folder named `MCT-Config`.

I did as suggested but I get this error:

```
Notebook Updated! ['v4.1.2']
An exception has occurred, use %tb to see the full traceback.
SystemExit: Please download Setup first!
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

**Comment by TheCaduceus** [comment]
@Sei969 Solution is already metinoned!
```
SystemExit: Please download Setup first!
```

**Comment by Sei969** [comment]
> @Sei969 Solution is already mentioned!
> 
> ```
> SystemExit: Please download Setup first!
> ```

Done but drives are not present in the file menu:

```
Notebook Updated! ['v4.1.2']

No rclone.conf file present in Root directory of My Drive to be copied to MCT-Config folder.
No Service Accounts available in Root directory of MyDrive to transport to MCT-Config folder.
No MEGA Credentials to transport from Root directory of My Drive into MCT-Config.
No GDTOT Crypt to transport from Root directory of My Drive into MCT-Config folder.
No HubDrive/DriveHub Crypt to restore from Root directory of My Drive into MCT-Config folder.
Import from MCT-Config:
Restore point available!
No Service Accounts in My Drive to restore.
Rclone config file already exits in local runtime! Do you want to replace it using one available in Google Drive's My Drive (MCT-Config folder)? 0 for No and 1 for Yes:
1
2022/08/12 08:23:12 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
Successfully restored & replaced the Rclone config file!
No GDTOT Crypt in My Drive to restore.
No HubDrive/DriveHub Crypt in My Drive to restore.
No MEGA Account Credentials available in your Google Drive's My Drive to restore!
```

**Comment by TheCaduceus** [comment]
@Sei969 It is detected!
```
Successfully restored & replaced the Rclone config file!
```
