### ISSUE TITLE
Using Service Accounts with GDrive remote disables it to be properly mounted

### ISSUE THREAD

**Issue by emersonjr** [TheCaduceus/Multi-Cloud-Transfer-Tool#16]
I'm trying to use my service accounts folder (followed the guide), but I'm able only to properly mount the remote drive in case I do not provide the service account file on rclone config. If I do, I press Mount, the folder shows up on the left side directory tree , but there's no droplist showing the drive's folders, it simply shows nothing.  
Do you have any ideas what might be going wrong here? Thanks in advance.

**Comment by TheCaduceus** [comment]
@emersonjr **Looks like your Service Accounts not have access to any Shared Drive or you forgot to add them in a Google Group**

** ⬇️Please follow my latest complete guide on Service Accounts:**
https://github.com/TheCaduceus/CloneBot_V2#-service-accounts

**Comment by emersonjr** [comment]
> @emersonjr **Looks like your Service Accounts not have access to any Shared Drive or you forgot to add them in a Google Group**
> 
> **⬇️Please follow my latest complete guide on Service Accounts:** https://github.com/TheCaduceus/CloneBot_V2#-service-accounts

I added them in a Google Group and granted them Manager access on a few Shared Drives of mine. But the files I want to copy are actually in My Drive, not in my Shared Drives. Is there anyway to give Manager access to the Group upon My Drive? or in this case I must copy My Drive contents to one of the Shared Drives and them copy it to Onedrive?

**Comment by TheCaduceus** [comment]
It
