### ISSUE TITLE
Transfer speed drastically dropping

### ISSUE THREAD

**Issue by emersonjr** [TheCaduceus/Multi-Cloud-Transfer-Tool#17]
Transfer speed started around 60MB/s, but later it just drops to this level, 1MB/s or less or just a bit more. Sometimes even less than 1KB/s is hit. Is there any specific reason for that?

![image](https://user-images.githubusercontent.com/8794425/184494447-2ca32ab1-adf0-461d-97b4-a5a025ebe162.png)

**Comment by TheCaduceus** [comment]
**@emersonjr Google Colab provides 70GB Storage that means you can transfer files or folder which is smaller than 70GB or you can use server sided copy option provided by Rclone. Or if you can't! then you can connect Colab to VPS or your local runtime by following Documents given by Google Colab Team.**

**Comment by alecaputo13** [comment]
@i-am-nut try to add --buffer-size 0M as argument
