### ISSUE TITLE
Google Account: Connection Error `DEBUG_MODE` Required!

### ISSUE THREAD

**Issue by Sei969** [TheCaduceus/Multi-Cloud-Transfer-Tool#18]
From time to time I get this error while using the script and even refreshing the browser or closing the session does not solve the problem:

```
An exception has occurred, use %tb to see the full traceback.

SystemExit: NoteBook is out-dated! Please update your Notebook to ['shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected', 'v4.1.2'], for getting latest new features.

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

**Comment by TheCaduceus** [comment]
@Sei969 It is reminder to use updated version of Notebook to get latest features and bug fixes. Access updated Notebook using below link:
```
https://colab.research.google.com/github/TheCaduceus/Multi-Cloud-Transfer-Tool/blob/main/Rclone.ipynb
```

**Comment by Sei969** [comment]
Nothing has changed, I still get the same error.

![Image 1](https://user-images.githubusercontent.com/6648848/184501483-29ddffbc-8a1f-41e8-b98c-ea595ad3e9ef.png)

**Comment by TheCaduceus** [comment]
@Sei969 **No Problem! you can use this option provided by Google Colab.**

![image](https://user-images.githubusercontent.com/87380104/184501811-d19289f6-4c6b-4309-883d-adf71e4d93a7.png)

**I tried, recreating the issue but it is working well:**

![image](https://user-images.githubusercontent.com/87380104/184501891-3c4c61c1-0dc6-49ba-a43c-d7f5bbc96078.png)
**Don't worry! I am actively working on `DEBUG_MODE` that will help users investigate the problem deeply.**

**Comment by Sei969** [comment]
Okay, now seems to be back to normal. If it happens again I will use the option you mentioned.
