### ISSUE TITLE
Can't Select the Clouds

### ISSUE THREAD

**Issue by rrfqi** [TheCaduceus/Multi-Cloud-Transfer-Tool#20]
last night it's still fine but now it can't shows the list of the clouds and I can't choose the clouds that I want to mount in colab, any how to fix this?
![54321](https://user-images.githubusercontent.com/35894106/185741026-613fb213-ff4a-46d6-acf3-a029bc8bf621.png)

**Comment by TheCaduceus** [comment]
@rrfqi Thanks! this error is now fixed.
