### ISSUE TITLE
[Req] About Youtube Download

### ISSUE THREAD

**Issue by SamadXYZ** [TheCaduceus/Multi-Cloud-Transfer-Tool#31]
Is it possible to add YT Download Quality button like TG MirrorLeech bot ???

**Comment by TheCaduceus** [comment]
@SamadXYZ yt-dlp supports quality-based downloads, you can run following command:
```
yt-dlp video_link_here --list-formats
```
and then:
```
cd destionation_path
yt-dlp video_link --format format_code_here
```

**Comment by SamadXYZ** [comment]
here, video only means 'no audio in video' ?

**Comment by TheCaduceus** [comment]
> here, video only means 'no audio in video' ?

Yes,
