### ISSUE TITLE
folder transfer

### ISSUE THREAD

**Issue by anumanu12321** [TheCaduceus/Multi-Cloud-Transfer-Tool#34]
when i transfer a folder with 2000 files to another google drive, i get error.
at that time the ram goes above 12gb terribly high and then the error occurs
![Untitled](https://user-images.githubusercontent.com/124474415/216796009-a92513be-9980-4132-b1b7-ea39aeff3100.jpg)
![Untitledu](https://user-images.githubusercontent.com/124474415/216796256-4dc05378-f6df-4b83-b1a8-b920a897c2ff.jpg)

**Comment by TheCaduceus** [comment]
@anumanu12321 for transferring large number of files, always use Rclone's transfer commands (directly) without involving mountpoints. Here is an example:
```
!rclone mode source_remote_name: destination_remote_name: --progress
```
In above example, replace `mode` with any mode like `copy` or `sync` and put required remote names between which you want to transfer files.

**Comment by anumanu12321** [comment]
!rclone mode source_remote_name: destination_remote_name: --progress

where i put this command?

**Comment by anumanu12321** [comment]
will i wait for your reply?

**Comment by anumanu12321** [comment]
progress flag is not working. so i used "--v stats 5s"
