### ISSUE TITLE
download quata is exceeded

### ISSUE THREAD

**Issue by anwerkhalidh** [TheCaduceus/Multi-Cloud-Transfer-Tool#36]
How to avoid this problem? 
iam using !rclone copy command. because folder contains huge amount of files. daily limit of google drive is 750gb. but this problem shows up even when less than 100gb complete.
iam using these flags      --stats-one-line -vv --stats 5s --tpslimit 25 --tpslimit-burst 10 --bwlimit 38M --max-transfer 600G 
can you suggest any changes for avoiding this problem?
![quata excedded](https://user-images.githubusercontent.com/125441525/218967645-6fc2a957-eebc-4890-8259-8a00b5aaf082.jpg)

**Comment by TheCaduceus** [comment]
Seems like Google temporary limited the source after seeing sudden transfers. If you are moving your files or folder within Google Drive, then I recommend you use only `--drive-server-side-across-configs ` as flag to prevent this and you can use service accounts to prevent hitting 750 GB limit, but service accounts can't prevent hitting file owner quota which applies for all downloaders.

**Comment by anwerkhalidh** [comment]
> Seems like Google temporary limited the source after seeing sudden transfers. If you are moving your files or folder within Google Drive, then I recommend you use only `--drive-server-side-across-configs ` as flag to prevent this and you can use service accounts to prevent hitting 750 GB limit. For more detailed resolution, you can ask the same on [**Rclone Forum**.](https://forum.rclone.org)

i am transfering one gdrive to another gdrive. this problem shows in destination gdrive

**Comment by TheCaduceus** [comment]
No problem, you can wait for 24 hours to let limit reset and from next time always use the flag I provided you above and also prefer using service accounts for cloning large amount of data.

**Comment by anwerkhalidh** [comment]
Is this flag only or should it be given along with the other flag I have given?

**Comment by TheCaduceus** [comment]
> Is this flag only or should it be given along with the other flag I have given?

You can use this flag only or with other flags like to prevent duplicate but it is not necessary.
