### ISSUE TITLE
compression ratio

### ISSUE THREAD

**Issue by anumanu12321** [TheCaduceus/Multi-Cloud-Transfer-Tool#39]
what is the compression ratio of rar? can we change that?

**Comment by TheCaduceus** [comment]
**RaR provides different levels to compress a given file, as you choose higher the level it will apply strong compression below:**
Store - `0`  (No compression)
Fastest - `1`
Fast - `2`
Normal - `3` (Default)
Good - `4`
Best - `5` (Highest compression)
**By default, MCT Tool apply normal level compression, as usual you can specify your own choice using following flag in args field:**
`-mX` where `X` is any number listed above.
