### ISSUE TITLE
Fatal error: mount not ready

### ISSUE THREAD

**Issue by nnhieu97** [TheCaduceus/Multi-Cloud-Transfer-Tool#40]
Hi. I got this error when trying to mount my rclone remotes. This code block takes 1 minute to run (while before it took me a few seconds). I checked the config file again, it works fine with remotes.
```
Enter Rclone remote name to continue:
abc
Select Action: 1 = Mount and 0 = Unmount:
1
2023/03/15 08:22:51 Fatal error: mount not ready
Mounted: /content/drives/abc
```

**Comment by asmydream** [comment]
me too 。How to solve？
