### ISSUE TITLE
Some suggestions during use

### ISSUE THREAD

**Issue by DifferentSparkler** [TheCaduceus/Multi-Cloud-Transfer-Tool#5]
![image](https://user-images.githubusercontent.com/38945550/170873327-4360fb41-728a-49b9-90f7-42121ecc7e62.png)
When I use the magnetic link to download, I can't view the download progress
Nor can colleagues perform other youtube download tasks
Can it be considered Aria2Ng for management Or add a download interface
So we can download both magnetic links and Youtube Videos

**Comment by TheCaduceus** [comment]
> ![image](https://user-images.githubusercontent.com/38945550/170873327-4360fb41-728a-49b9-90f7-42121ecc7e62.png) When I use the magnetic link to download, I can't view the download progress Nor can colleagues perform other youtube download tasks Can it be considered Aria2Ng for management Or add a download interface So we can download both magnetic links and Youtube Videos

It is must to type ``Exit`` after adding Magnet links, then program will automatically start downloading of all added magnet links. Thanks for your suggestion, will work on it too.
