### ISSUE TITLE
Heroku Support

### ISSUE THREAD

**Issue by arjung24** [TheCaduceus/Multi-Cloud-Transfer-Tool#7]
Can you make this project "MCT Tool" heroku deployable??

**Comment by TheCaduceus** [comment]
Yup, I can make it deployable to Heroku, If you check my GitHub profile their is a "Jupyter Server Heroku" which is already deployable to Heroku but main problem is that I can't maintain same Ui as in Colab. But anyone familier with commands can easily use the ipynb file in Jupyter Server Heroku repository that MCT Tool use.

**Comment by TheCaduceus** [comment]
> Can you make this project "MCT Tool" heroku deployable??

Yup, I can make it deployable to Heroku, If you check my GitHub profile their is a "Jupyter Server Heroku" which is already deployable to Heroku but main problem is that I can't maintain same Ui as in Colab. But anyone familier with commands can easily use the ipynb file in Jupyter Server Heroku repository that MCT Tool use.

**Comment by arjung24** [comment]
u can try heroku with telegram bot. then no ui is needed i think.

**Comment by TheCaduceus** [comment]
@arjung24 Alright! Thanks for your suggestion! ❤️

**Comment by arjung24** [comment]
i mean is it possible (Colab+heroku+Telegram bot). That would be great. u developers may know that. lots of love brother.

**Comment by arjung24** [comment]
> i mean is it possible (Colab+heroku+Telegram bot). That would be great. u developers may know that. lots of love brother.

Is it done brother??

**Comment by TheCaduceus** [comment]
@arjung24 Nope! Will start doing after sometimes.

**Comment by arjung24** [comment]
Oh. You just closed the issue. That's why i thought, may be you implemented the feature.😊😊
