### ISSUE TITLE
Drives Mounted Problem

### ISSUE THREAD

**Issue by massmia** [TheCaduceus/Multi-Cloud-Transfer-Tool#8]
I mounted drives, but why didn't show any files/folders on all drives?

![Screenshot (96)_LI](https://user-images.githubusercontent.com/98101010/173213407-6ed4bb4a-350f-428e-855a-f926897edc12.jpg)

**Comment by TheCaduceus** [comment]
> I mounted drives, but why didn't show any files/folders on all drives?
> 
> ![Screenshot (96)_LI](https://user-images.githubusercontent.com/98101010/173213407-6ed4bb4a-350f-428e-855a-f926897edc12.jpg)

It seems your Rclone config file is old or its auth token expired-> Try to create it again. If your mounted remotes getting disconnected again then unmount it then mount it again.

**Comment by massmia** [comment]
um I just  created all 3 drives' rclone file about 20mins ago

**Comment by TheCaduceus** [comment]
@massmia Then umount and mount them again! Google Colab kills all Rclone process when a code is stopped that's why it happens.
