### ISSUE TITLE
Fetching rclone Config file Isssue

### ISSUE THREAD

**Issue by massmia** [TheCaduceus/Multi-Cloud-Transfer-Tool#9]
Now I am unable to connect any drive.

[NB: I just create rclone file yesterday after your mct update. ]

![1](https://user-images.githubusercontent.com/98101010/178407673-d54a5b46-8e99-423c-ab1c-a1a792321155.png)
![2](https://user-images.githubusercontent.com/98101010/178407678-4a74ed72-4abe-4f95-956b-77563e43cbdd.png)
![3](https://user-images.githubusercontent.com/98101010/178407680-745ea64d-c961-424e-8489-0a9252bc8795.png)
![4](https://user-images.githubusercontent.com/98101010/178407681-ea8baa7d-5919-40cb-b1d2-bfc694c7996a.png)
![5](https://user-images.githubusercontent.com/98101010/178407685-1df0b9e5-7e9c-4d38-ba42-562cc2fdb549.png)

**Comment by TheCaduceus** [comment]
> Now I am unable to connect any drive.
> 
> [NB: I just create rclone file yesterday after your mct update. ]
> 
> ![1](https://user-images.githubusercontent.com/98101010/178407673-d54a5b46-8e99-423c-ab1c-a1a792321155.png) ![2](https://user-images.githubusercontent.com/98101010/178407678-4a74ed72-4abe-4f95-956b-77563e43cbdd.png) ![3](https://user-images.githubusercontent.com/98101010/178407680-745ea64d-c961-424e-8489-0a9252bc8795.png) ![4](https://user-images.githubusercontent.com/98101010/178407681-ea8baa7d-5919-40cb-b1d2-bfc694c7996a.png) ![5](https://user-images.githubusercontent.com/98101010/178407685-1df0b9e5-7e9c-4d38-ba42-562cc2fdb549.png)

Looks like you are not using latest version. First uncheck all columns and then run code [Use Latest NoteBook]. If I talk about problem, then it is causing because following line is missing in given code, which is added in latest release:
![image](https://user-images.githubusercontent.com/87380104/178408503-f9485309-90e4-48e5-a015-99a75aed1429.png)

**Comment by massmia** [comment]
I'm using latest version

**Comment by TheCaduceus** [comment]
@massmia Then this problem should be resolved
